/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppGooglelogin {}
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface WalkDetail {
    'name': string;
  }
  interface WalkModal {}
}

declare global {


  interface HTMLAppGoogleloginElement extends Components.AppGooglelogin, HTMLStencilElement {}
  var HTMLAppGoogleloginElement: {
    prototype: HTMLAppGoogleloginElement;
    new (): HTMLAppGoogleloginElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLWalkDetailElement extends Components.WalkDetail, HTMLStencilElement {}
  var HTMLWalkDetailElement: {
    prototype: HTMLWalkDetailElement;
    new (): HTMLWalkDetailElement;
  };

  interface HTMLWalkModalElement extends Components.WalkModal, HTMLStencilElement {}
  var HTMLWalkModalElement: {
    prototype: HTMLWalkModalElement;
    new (): HTMLWalkModalElement;
  };
  interface HTMLElementTagNameMap {
    'app-googlelogin': HTMLAppGoogleloginElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'walk-detail': HTMLWalkDetailElement;
    'walk-modal': HTMLWalkModalElement;
  }
}

declare namespace LocalJSX {
  interface AppGooglelogin extends JSXBase.HTMLAttributes<HTMLAppGoogleloginElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'name'?: string;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface WalkDetail extends JSXBase.HTMLAttributes<HTMLWalkDetailElement> {
    'name'?: string;
  }
  interface WalkModal extends JSXBase.HTMLAttributes<HTMLWalkModalElement> {}

  interface IntrinsicElements {
    'app-googlelogin': AppGooglelogin;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'walk-detail': WalkDetail;
    'walk-modal': WalkModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


